version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tubes-kaa
    container_name: laravel-tubes-ka
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=tubes_ka
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "9077:80"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tubes_ka
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pemfra-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "9088:80"
    depends_on:
      - db
    networks:
      - laravel-net

  node:
    image: node:18
    ports:
      - "5173:5173"
    container_name: laravel-node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel-net
    command: sh -c "npm install && npm i vite && npm run dev --host"
    depends_on:
      - app

networks:
  laravel-net:

volumes:
  mysql_data:



# version: '3.8'

# services:
#   laravel-docker:
#     container_name: laravel-docker
#     build: .
#     volumes:
#     - ./pemfra-final-project:/var/www/html
#     ports:
#       - 9000:80
#     environment:
#       - DB_CONNECTION=mysql
#       - DB_HOST=mysql_db
#       - DB_PORT=3306
#       - DB_DATABASE=laravel
#       - DB_USERNAME=root
#       - DB_PASSWORD=root

#   mysql_db:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: laravel
#     ports:
#       - 3307:3306
#     volumes:
#       - mysql_data:/var/lib/mysql

#   phpmyadmin:
#     image: phpmyadmin:latest
#     ports:
#       - 9001:80
#     environment:
#       - PMA_HOST=mysql_db
#       - PMA_USER=root
#       - PMA_PASSWORD=root
#       - PMA_ARBITRARY=1

# volumes:
#   mysql_data:



# version: '3.8'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: laravel-app
#     container_name: laravel_app
#     ports:
#       - "8070:80" # Port 8070 untuk akses aplikasi Laravel
#     volumes:
#       - .:/var/www/html
#     environment:
#       - DB_CONNECTION=mysql
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - DB_DATABASE=laravel
#       - DB_USERNAME=sail
#       - DB_PASSWORD=password

#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: sail
#       MYSQL_PASSWORD: password
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "3306:3306"

# volumes:
#   mysql_data:


# version: '3.8'

# services:
#   laravel-docker:
#     container_name: laravel-docker
#     build: .
#     volumes:
#     - ./pemfra-final-project:/var/www/html
#     ports:
#       - 9000:80
#     environment:
#       - DB_CONNECTION=mysql
#       - DB_HOST=mysql_db
#       - DB_PORT=3306
#       - DB_DATABASE=laravel
#       - DB_USERNAME=root
#       - DB_PASSWORD=root

#   mysql_db:
#     image: mysql:latest
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: laravel
#     ports:
#       - 3307:3306
#     volumes:
#       - mysql_data:/var/lib/mysql

#   phpmyadmin:
#     image: phpmyadmin:latest
#     ports:
#       - 9001:80
#     environment:
#       - PMA_HOST=mysql_db
#       - PMA_USER=root
#       - PMA_PASSWORD=root
#       - PMA_ARBITRARY=1

# volumes:
#   mysql_data:



# version: '3.8'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: laravel-app
#     container_name: laravel_app
#     ports:
#       - "8070:80" # Port 8070 untuk akses aplikasi Laravel
#     volumes:
#       - .:/var/www/html
#     environment:
#       - DB_CONNECTION=mysql
#       - DB_HOST=mysql
#       - DB_PORT=3306
#       - DB_DATABASE=laravel
#       - DB_USERNAME=sail
#       - DB_PASSWORD=password

#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: sail
#       MYSQL_PASSWORD: password
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "3306:3306"

# volumes:
#   mysql_data:
